# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xci
# IP: The module: 'arty_linux_p1_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xci
# IP: The module: 'arty_linux_p1_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_linux_p1_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
