# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.cache/wt [current_project]
set_property parent.project_path /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/hdl/arty_linux_p1_wrapper.v
add_files /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/arty_linux_p1.bd
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_clk_wiz_0_0/arty_linux_p1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_clk_wiz_0_0/arty_linux_p1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_clk_wiz_0_0/arty_linux_p1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_mig_7series_0_0/arty_linux_p1_mig_7series_0_0/user_design/constraints/arty_linux_p1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_mig_7series_0_0/arty_linux_p1_mig_7series_0_0/user_design/constraints/arty_linux_p1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_mig_7series_0_0/arty_linux_p1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_axi_intc_0/arty_linux_p1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_axi_intc_0/arty_linux_p1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_axi_intc_0/arty_linux_p1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_mdm_1_0/arty_linux_p1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_mdm_1_0/arty_linux_p1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_rst_mig_7series_0_83M_0/arty_linux_p1_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_rst_mig_7series_0_83M_0/arty_linux_p1_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_rst_mig_7series_0_83M_0/arty_linux_p1_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_uartlite_0_0/arty_linux_p1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_uartlite_0_0/arty_linux_p1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_uartlite_0_0/arty_linux_p1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_ethernetlite_0_0/arty_linux_p1_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_ethernetlite_0_0/arty_linux_p1_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_ethernetlite_0_0/arty_linux_p1_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_ethernetlite_0_0/arty_linux_p1_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_timer_0_0/arty_linux_p1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_timer_0_0/arty_linux_p1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_10/bd_de01_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_19/bd_de01_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_22/bd_de01_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_23/bd_de01_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_24/bd_de01_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_25/bd_de01_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_26/bd_de01_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_27/bd_de01_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_20/bd_de01_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_21/bd_de01_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_11/bd_de01_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_12/bd_de01_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_13/bd_de01_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_14/bd_de01_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_15/bd_de01_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_2/bd_de01_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_3/bd_de01_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_4/bd_de01_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_5/bd_de01_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_6/bd_de01_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_1/bd_de01_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/bd_0/ip/ip_1/bd_de01_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_xbar_0/arty_linux_p1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_dlmb_v10_0/arty_linux_p1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_dlmb_v10_0/arty_linux_p1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_ilmb_v10_0/arty_linux_p1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_ilmb_v10_0/arty_linux_p1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_dlmb_bram_if_cntlr_0/arty_linux_p1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_ilmb_bram_if_cntlr_0/arty_linux_p1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_lmb_bram_0/arty_linux_p1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_0_0/arty_linux_p1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_0_0/arty_linux_p1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_0_0/arty_linux_p1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_1_0/arty_linux_p1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_1_0/arty_linux_p1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_1_0/arty_linux_p1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_2_0/arty_linux_p1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_2_0/arty_linux_p1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_2_0/arty_linux_p1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_quad_spi_0_0/arty_linux_p1_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_quad_spi_0_0/arty_linux_p1_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_quad_spi_0_0/arty_linux_p1_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/ip/arty_linux_p1_axi_quad_spi_0_0/arty_linux_p1_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/arty_linux_p1_ooc.xdc]
set_property is_locked true [get_files /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/sources_1/bd/arty_linux_p1/arty_linux_p1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/constrs_1/new/eth_ref_clk.xdc
set_property used_in_implementation false [get_files /home/ramprasad/arty_projects_10-7-2017/arty_linux/arty_linux.srcs/constrs_1/new/eth_ref_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top arty_linux_p1_wrapper -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef arty_linux_p1_wrapper.dcp

catch { report_utilization -file arty_linux_p1_wrapper_utilization_synth.rpt -pb arty_linux_p1_wrapper_utilization_synth.pb }
