# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/arty_linux_p1/arty_linux_p1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1 || ORIG_REF_NAME==arty_linux_p1}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_clk_wiz_0_0/arty_linux_p1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_clk_wiz_0_0 || ORIG_REF_NAME==arty_linux_p1_clk_wiz_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_mig_7series_0_0/arty_linux_p1_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_mig_7series_0_0 || ORIG_REF_NAME==arty_linux_p1_mig_7series_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_0/arty_linux_p1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_microblaze_0_0 || ORIG_REF_NAME==arty_linux_p1_microblaze_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_axi_periph_0/arty_linux_p1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==arty_linux_p1_microblaze_0_axi_periph_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_axi_intc_0/arty_linux_p1_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==arty_linux_p1_microblaze_0_axi_intc_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_microblaze_0_xlconcat_0/arty_linux_p1_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==arty_linux_p1_microblaze_0_xlconcat_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_mdm_1_0/arty_linux_p1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_mdm_1_0 || ORIG_REF_NAME==arty_linux_p1_mdm_1_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_rst_mig_7series_0_83M_0/arty_linux_p1_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==arty_linux_p1_rst_mig_7series_0_83M_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_uartlite_0_0/arty_linux_p1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_uartlite_0_0 || ORIG_REF_NAME==arty_linux_p1_axi_uartlite_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_ethernetlite_0_0/arty_linux_p1_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_ethernetlite_0_0 || ORIG_REF_NAME==arty_linux_p1_axi_ethernetlite_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_timer_0_0/arty_linux_p1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_timer_0_0 || ORIG_REF_NAME==arty_linux_p1_axi_timer_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_smc_0/arty_linux_p1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_smc_0 || ORIG_REF_NAME==arty_linux_p1_axi_smc_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_xbar_0/arty_linux_p1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_xbar_0 || ORIG_REF_NAME==arty_linux_p1_xbar_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_dlmb_v10_0/arty_linux_p1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_dlmb_v10_0 || ORIG_REF_NAME==arty_linux_p1_dlmb_v10_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_ilmb_v10_0/arty_linux_p1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_ilmb_v10_0 || ORIG_REF_NAME==arty_linux_p1_ilmb_v10_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_dlmb_bram_if_cntlr_0/arty_linux_p1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_linux_p1_dlmb_bram_if_cntlr_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_ilmb_bram_if_cntlr_0/arty_linux_p1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_linux_p1_ilmb_bram_if_cntlr_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_lmb_bram_0/arty_linux_p1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_lmb_bram_0 || ORIG_REF_NAME==arty_linux_p1_lmb_bram_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_0_0/arty_linux_p1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_gpio_0_0 || ORIG_REF_NAME==arty_linux_p1_axi_gpio_0_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_1_0/arty_linux_p1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_gpio_1_0 || ORIG_REF_NAME==arty_linux_p1_axi_gpio_1_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_gpio_2_0/arty_linux_p1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_gpio_2_0 || ORIG_REF_NAME==arty_linux_p1_axi_gpio_2_0}]

# IP: bd/arty_linux_p1/ip/arty_linux_p1_axi_quad_spi_0_0/arty_linux_p1_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_linux_p1_axi_quad_spi_0_0 || ORIG_REF_NAME==arty_linux_p1_axi_quad_spi_0_0}]

# XDC: bd/arty_linux_p1/arty_linux_p1_ooc.xdc
